### ISSUE TITLE
Bad parsing when using mdzk with mdbook-toc

### ISSUE THREAD

**Issue by arcticlimer** [mdzk-rs/mdzk#38]
I would like to use [mdbook-toc](https://github.com/badboy/mdbook-toc) to automatically add table of contents to my notes, but when I set it inside as a preprocessor it breaks mdzk parsing (backlinks doesn't work, metadata on top of notes doesn't get parsed).

Is there a way to make them both work together?

Current configuration:
```toml
[mdzk]
authors = ["author"]
ignore = []
language = "en"
multilingual = false
src = "notes"
title = "mdzk"
backlinks-header = "Backlinks"

[build]
create-missing = false
build-dir = "book"

[output.html]
no-section-label = true

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
```

**Comment by kmaasrud** [comment]
I suspect this happens because mdbook-toc is run before our internal preprocessors, and it modifies the content in a way that is incompatible with them. mdbook-toc modifies the pulldown-cmark Events and exports them to CommonMark again with pulldown_cmark_to_cmark, which might cause the issue...

Ideally, our preprocessors should be run first, so I will investigate if we can force the order somehow. If that is unsuccessful, I'll have to check the output of mdbook-toc and why it breaks the rest of the preprocessors.

Thanks for reporting this issue! I will try and fix it as soon as I can :smile:

**Comment by kmaasrud** [comment]
You should now (mdzk HEAD) be able to run `mdbook-toc` using the config above without problem.

Beware that the extra fields you've supplied (`command` and `renderer`) will be ignored. I've introduced a new field `build.preprocessors` in `mdzk.toml` that we can control the order of, and I'm simply converting the `[preprocessor.<name>]` pattern into that field. That means you can also change your config to:

```toml
[build]
# ...
preprocessors = ["toc"]
# ...
```

if you want. The fix will be released as part of 0.4.3. Be sure to reopen the issue if you have further problems 😄
