### ISSUE TITLE
Feature request mermaid processor?

### ISSUE THREAD

**Issue by alanmbarr** [mdzk-rs/mdzk#64]
I'd like to use mermaid [diagrams](https://notes.alanmbarr.com/Various%20Thoughts/OpenAPI%20Ecosystem.html#workflows) for my digital garden. Is this on the roadmap or is it better to hook in an existing processor?

**Comment by theFr1nge** [comment]
I personally use the existing preprocessor [mdbook-mermaid](https://github.com/badboy/mdbook-mermaid), which works just fine. Here is my mdzk.toml:

```toml
[mdzk]
authors = ["Yigit Colakoglu"]
ignore = ["Excalidraw", "Images"]
language = "en"
multilingual = false
src = "notes"
title = "Obsidian Wiki"
description = "An online version of my Zettelkasten"

[output.html.fold]
enable = true
level = 1

[build]
preprocessors = ["mermaid"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
```
