### ISSUE TITLE
The mermaid preprocessor breaks backlinks

### ISSUE THREAD

**Issue by theFr1nge** [mdzk-rs/mdzk#65]
When trying to use the mermaid preprocessor with the following configuration:

```toml
[mdzk]
authors = ["Yigit Colakoglu"]
ignore = ["Excalidraw", "Images"]
language = "en"
multilingual = false
src = "notes"
title = "Obsidian Wiki"
description = "An online version of my Zettelkasten"

[output.html.fold]
enable = true
level = 1

[build]
preprocessors = ["mermaid"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
```

The backlinks are added successfully, but they are not turned into hyperlinks in HTML correctly as you can see in the image below:

![CE959C92-88E3-42CA-8243-68C3AF4FEEC0](https://user-images.githubusercontent.com/30830979/146024896-1f86bcf7-6baa-498a-b756-769ba5d82c13.jpeg)
